# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pipenv lock -r > requirements.txt
  displayName: 'Create requirements.txt from Pipfile'

- script: pip install -r requirements.txt
  displayName: 'Install requirements.txt'

- script: nosetests
  displayName: 'Run unittests'
