apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-battleforcastile-match-recorder-deployment
  labels:
    name: {{ .Release.Name }}-battleforcastile-match-recorder
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-battleforcastile-match-recorder
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-battleforcastile-match-recorder
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-cloudsql-instance-credentials
          secret:
            secretName: {{ .Release.Name }}-cloudsql-instance-credentials
      containers:
        - name: {{ .Release.Name }}-cloudsql-proxy
          image: "{{ .Values.image_cloudsql_proxy.repository }}:{{ .Values.image_cloudsql_proxy.tag }}"
          imagePullPolicy: {{ .Values.image_cloudsql_proxy.pullPolicy }}
          command: ["/cloud_sql_proxy",
                    "-instances={{ .Values.database.instance_connection_name}}=tcp:5432",
            # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
            # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
            # "-ip_address_types=PRIVATE",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: {{ .Release.Name }}-cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: {{ .Release.Name }}-battleforcastile-match-recorder
          image: "{{ .Values.image_battleforcastile_match_recorder.repository }}:{{ .Values.image_battleforcastile_match_recorder.tag }}"
          imagePullPolicy: {{ .Values.image_battleforcastile_match_recorder.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image_battleforcastile_match_recorder.container_port }}
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-battleforcastile-match-recorder-secrets
                  key: secret_key
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-battleforcastile-match-recorder-secrets
                  key: sqlalchemy_database_uri
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
