"""empty message

Revision ID: 9fa632f808f9
Revises: befd13cf9477
Create Date: 2019-08-20 22:42:51.019323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa632f808f9'
down_revision = 'befd13cf9477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn', sa.Column('num_cards_in_hand_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turn', 'num_cards_in_hand_left')
    # ### end Alembic commands ###
