"""empty message

Revision ID: cda10401f709
Revises: 
Create Date: 2019-08-24 13:44:54.892494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda10401f709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_user_username', sa.String(length=80), nullable=False),
    sa.Column('first_user_character', sa.Text(), nullable=False),
    sa.Column('second_user_username', sa.String(length=80), nullable=True),
    sa.Column('second_user_character', sa.Text(), nullable=True),
    sa.Column('winner_username', sa.String(length=80), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('hero_username', sa.String(length=80), nullable=False),
    sa.Column('enemy_username', sa.String(length=80), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('num_cards_in_hand_left', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'match_id', 'hero_username', name='unique_constraint_commit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn')
    op.drop_table('match')
    # ### end Alembic commands ###
