"""empty message

Revision ID: fe69de692c34
Revises: cda10401f709
Create Date: 2019-08-28 21:12:37.036266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe69de692c34'
down_revision = 'cda10401f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'started')
    # ### end Alembic commands ###
