apiVersion: v1
kind: Secret
metadata:
  name: battleforcastile-match-recorder-secrets
type: Opaque
data:
  secret_key: {{ .Values.secretkey }}
  sqlalchemy_database_uri: {{ .Values.sqlalchemydatabaseuri }}
